"""Synthetic demo scenario. EVERYTHING HERE IS FAKE DATA, generated to exercise the dashboard.

Scenario (invented): a support tool asks a decision model "Is this refund request eligible under the
written policy?" (noul) and "Which team should handle this?" (choice) for ~110 tickets/day over 28 days.
- Day 19: the (mock) provider version changes from mock-decider-v1 to mock-decider-v2.
- Day 22 onward, chat tickets start carrying customer-written arguments ("I'm sure this qualifies...")
  that push the mock toward 'yes' - modelled loosely on the failure mode JevAdvBench reports
  (https://arxiv.org/abs/2609.31142). The numbers below are NOT measurements of any real model.
- Ground truth arrives with a 2-day lag for ~85% of tickets (CSV export from the "refund system").
"""
from __future__ import annotations

import csv
import random
from datetime import datetime, timedelta, timezone

from .monitor import Monitor
from .providers import MockProvider

QUESTIONS = {
    "refund_eligible": {
        "type": "noul",
        "instructions": "Is this refund request eligible under the written refund policy in `policy`?",
        "criteria": {"true": "Meets every condition in the policy", "false": "Fails at least one condition"},
    },
    "route": {
        "type": "choice",
        "instructions": "Which team should handle this ticket?",
        "criteria": {"billing": "Payments, invoicing, refunds", "technical": "Bugs, outages, integrations",
                     "sales": "Pricing, upgrades, new accounts"},
    },
}

END = datetime(2026, 10, 1, 18, 0, tzinfo=timezone.utc)
DAYS = 28


def generate(db_path: str, outcomes_csv: str, seed: int = 7, per_day: int = 110, with_shadow: bool = True):
    rng = random.Random(seed)
    primary = MockProvider(model_name="mock-decider-v1")
    shadow = [MockProvider(model_name="mock-alt-provider", skill=2.0, overconfidence=0.9,
                           use_sim_profile=False, name="mock-alt")] if with_shadow else []
    mon = Monitor(db_path, provider=primary, shadow_providers=shadow)
    start = END - timedelta(days=DAYS - 1)
    outcome_rows = []
    for d in range(DAYS):
        day = start + timedelta(days=d)
        n = per_day + rng.randint(-15, 15)
        for i in range(n):
            ts = (day.replace(hour=0) + timedelta(seconds=rng.randint(0, 86399))).isoformat()
            channel = "chat" if rng.random() < 0.45 else "email"
            eligible = rng.random() < 0.38
            route = rng.choices(["billing", "technical", "sales"], [0.55, 0.3, 0.15])[0]
            version = "mock-decider-v1" if d < 18 else "mock-decider-v2"
            profile = {"model": version, "skill": 2.5 if d < 18 else 2.35, "bias": -0.2, "overconfidence": 1.0}
            if channel == "chat" and d >= 21:
                profile.update(bias=1.25, overconfidence=1.25)  # argued input pushes toward yes
            state = {"ticket_id": f"SYN-{d:02d}-{i:04d}", "channel": channel,
                     "text": "[synthetic ticket text]", "policy": "[synthetic policy]",
                     "_sim": {**profile, "truth": {"refund_eligible": eligible, "route": route}}}
            res = mon.decide(state, QUESTIONS, model="jev-1.13.0-pinned (mock)", segment=f"channel={channel}",
                             thresholds={"refund_eligible": 0.5}, ts=ts)
            # ground truth lags 2 days and covers ~85% of tickets
            if d <= DAYS - 3 and rng.random() < 0.85:
                outcome_rows.append((res["decision_id"], "refund_eligible", "yes" if eligible else "no"))
                outcome_rows.append((res["decision_id"], "route", route))
    with open(outcomes_csv, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["decision_id", "question_key", "actual"])
        w.writerows(outcome_rows)
    return len(outcome_rows)


CHECK_SAMPLE_HEADER = ("SYNTHETIC sample data for `calibrate check`, generated by calibrate.synth.make_check_sample "
                       "(seed {seed}). Invented refund-approval scenario; not measurements of any real model.")


def make_check_sample(path: str, n: int = 2400, seed: int = 11, end: datetime | None = None):
    """Write a SYNTHETIC decisions export for `calibrate check` (one row per decision).

    Invented scenario: an AI step approves/denies refund requests (yes/no) over 60 days.
    - ~40% of requests are truly eligible.
    - model refund-v1 until day 40, then refund-v2, which is noticeably more overconfident.
    - chat requests skew toward 'yes' (customers argue their case), so false accepts are higher there.
    - a tiny phone segment exists to show the small-n flag.
    """
    import math
    rng = random.Random(seed)
    end = end or datetime(2026, 10, 1, 23, 0, tzinfo=timezone.utc)
    days = 60
    start = end - timedelta(days=days - 1)
    rows = []
    for i in range(n):
        d = int(rng.random() * days)
        ts = (start.replace(hour=0, minute=0, second=0) + timedelta(days=d, seconds=rng.randint(0, 86399)))
        u = rng.random()
        channel = "chat" if u < 0.40 else ("phone" if u < 0.43 else "email")
        version = "refund-v1" if d < 40 else "refund-v2"
        eligible = rng.random() < 0.40
        skill, sigma, prior = 1.6, 1.25, math.log(0.40 / 0.60)
        x = skill * (1 if eligible else -1) + rng.gauss(0, sigma)
        logit_cal = 2 * skill * x / sigma ** 2 + prior    # the calibrated posterior log-odds
        conf, shift = (1.0, 0.0) if version == "refund-v1" else (1.6, 0.2)  # v2: overconfident
        if channel == "chat":
            shift += 0.9                                    # argued chat requests push toward 'yes'
        p = 1 / (1 + math.exp(-(conf * logit_cal + shift)))
        p = min(max(round(p, 3), 0.001), 0.999)
        thr = 0.5
        rows.append((ts, f"SYN-{i:05d}", channel, version, p, thr, "yes" if p >= thr else "no",
                     "yes" if eligible else "no"))
    rows.sort(key=lambda r: r[0])
    with open(path, "w", newline="") as f:
        f.write("# " + CHECK_SAMPLE_HEADER.format(seed=seed) + "\n")
        w = csv.writer(f)
        w.writerow(["timestamp", "decision_id", "segment", "model_version", "probability", "threshold",
                    "decision", "outcome"])
        for ts, did, ch, ver, p, thr, dec, out in rows:
            w.writerow([ts.strftime("%Y-%m-%dT%H:%M:%SZ"), did, f"channel={ch}", ver, f"{p:.3f}", thr, dec, out])
    return len(rows)
